######################################################################
# Automatically generated by qmake (2.01a) So. Nov 7 15:41:50 2010
######################################################################

TEMPLATE = app
TARGET = ClassCluster
INCLUDEPATH += .
QT += gui
QT += widgets
CONFIG += QT
CONFIG += debug

# Input
HEADERS += Calculation.h \
    particle.h \
    picture.h
SOURCES += main.cpp Calculation.cpp \
    picture.cpp
