######################################################################
# Automatically generated by qmake (2.01a) So. Nov 21 06:11:15 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
